import assert from 'node:assert/strict';
import {dates,charges,actualPayments,saved,monthly,savingMonthly,validWorkspace,cancelSubscription} from '../lib/finance.ts';
import {PrivateSessionStorage,installSessionLifecycle} from '../lib/private-session.ts';
import {thisDeviceOptions,decodeBase64url,encodeBase64url} from '../lib/passkey-options.ts';
const p={id:'p',start:'2026-01-31',end:null,amount:20,cycle:'monthly',day:31,card:'Chase'};
const i={id:'i',name:'Servicio',kind:'subscription',color:'#315cf5',variable:false,notes:'',periods:[p],savings:[],payments:[]};
assert.equal(dates(p,2026)[1],'2026-02-28');assert.equal(dates({...p,start:'2024-01-31'},2024)[1],'2024-02-29');
assert.deepEqual(dates({...p,cycle:'annual'},2026),['2026-01-31']);
assert.equal(charges(i,2026).length,12);assert.equal(actualPayments([i],2026,'2026-10-07').length,0);
const paid={id:'x',due:'2026-02-28',date:'2026-03-02',amount:31.12,card:'Otra',status:'paid',note:''};
const edited={...i,payments:[paid]};assert.equal(charges(edited,2026)[1].amount,31.12);assert.equal(actualPayments([edited],2026,'2026-03-01').length,0);assert.equal(actualPayments([edited],2026,'2026-03-02')[0].amount,31.12);
assert.equal(charges({...edited,periods:[{...p,amount:40}]},2026)[1].amount,31.12);
const canceled={...edited,periods:[{...p,end:'2026-06-01'}],savings:[{id:'s',from:'2026-06-01',to:null,amount:20,cycle:'monthly',day:31,anchor:p.start}]};
assert.equal(charges(canceled,2026).length,5);assert.equal(monthly(canceled,'2026-10-01'),0);assert.equal(saved(canceled,2026,'2026-10-07'),80);assert.equal(savingMonthly(canceled,'2026-10-01'),20);
const resumed={...canceled,periods:[...canceled.periods,{...p,id:'p2',start:'2026-09-01'}],savings:[{...canceled.savings[0],to:'2026-09-01'}]};assert.equal(saved(resumed,2026,'2026-12-31'),60);assert.equal(charges(resumed,2026).length,9);
const annualCanceled={...i,periods:[{...p,cycle:'annual',end:'2026-06-01'}],savings:[{...canceled.savings[0],cycle:'annual'}]};assert.equal(saved(annualCanceled,2026,'2026-12-31'),0);assert.equal(saved(annualCanceled,2027,'2027-02-01'),20);
const crossYear={...i,payments:[{...paid,due:'2025-12-31',date:'2026-01-02'}]};assert.equal(actualPayments([crossYear],2026,'2026-01-03').length,1);
assert.equal(validWorkspace({items:[i]}),true);assert.equal(validWorkspace({items:[{...i,periods:[{...p,amount:-1}]}]}),false);assert.equal(validWorkspace({items:[{...i,periods:[{...p,start:'2026-02-31'}]}]}),false);
const octoberPaid={id:'oct',due:'2026-10-07',date:'2026-10-07',amount:12.99,card:'Chase',status:'paid',note:''};
const beforeCancellation={...i,periods:[{...p,start:'2026-01-01',day:7,amount:12.99}],payments:[octoberPaid]};
const sameDayCancellation=cancelSubscription(beforeCancellation,'2026-10-07',12.99,'2026-10-07');
assert.deepEqual(sameDayCancellation.payments,beforeCancellation.payments);
assert.equal(validWorkspace({items:[sameDayCancellation]}),true);
assert.equal(actualPayments([sameDayCancellation],2026,'2026-10-07')[0].amount,12.99);
assert.equal(charges(sameDayCancellation,2026).find(c=>c.due==='2026-10-07').status,'paid');
assert.equal(charges(sameDayCancellation,2026).some(c=>c.due==='2026-11-07'),false);
assert.equal(saved(sameDayCancellation,2026,'2026-10-07'),0);
assert.equal(saved(sameDayCancellation,2026,'2026-11-06'),0);
assert.equal(saved(sameDayCancellation,2026,'2026-11-07'),12.99);
assert.equal(saved(sameDayCancellation,2026,'2026-12-31'),25.98);
const noPaymentCancellation=cancelSubscription({...beforeCancellation,payments:[]},'2026-10-07',12.99,'2026-10-07');
assert.equal(saved(noPaymentCancellation,2026,'2026-10-07'),12.99);
assert.throws(()=>cancelSubscription({...beforeCancellation,payments:[{...octoberPaid,due:'2026-11-07'}]},'2026-10-07',12.99,'2026-10-07'),/posterior/);
const annualSameDay=cancelSubscription({...beforeCancellation,periods:[{...p,start:'2025-10-07',day:7,amount:120,cycle:'annual'}]},'2026-10-07',120,'2026-10-07');
assert.equal(saved(annualSameDay,2026,'2026-12-31'),0);
assert.equal(saved(annualSameDay,2027,'2027-10-07'),120);
// Explicit close erases credentials synchronously, including late responses.
const memory=new PrivateSessionStorage();
const firstGeneration=memory.beginAuthentication();memory.setItem('auth','test-session');
assert.equal(memory.getItem('auth'),'test-session');memory.lock();
assert.equal(memory.getItem('auth'),null);assert.equal(memory.isCurrent(firstGeneration),false);
memory.setItem('auth','late-response');assert.equal(memory.getItem('auth'),null);
const secondGeneration=memory.beginAuthentication();memory.setItem('auth','new-session');
memory.ceremonies++;assert.equal(memory.lock(),false);assert.equal(memory.getItem('auth'),'new-session');
memory.ceremonies--;memory.lock();assert.equal(memory.getItem('auth'),null);
assert.equal(memory.isCurrent(secondGeneration),false);
memory.beginAuthentication();memory.ceremonies++;memory.lock(true);
assert.equal(memory.getItem('auth'),null);assert.equal(memory.locked,true);
assert.equal(new PrivateSessionStorage().getItem('auth'),null);
const lifecycle=new EventTarget(),liveSession=new PrivateSessionStorage();
liveSession.setItem('auth','live-session');const uninstall=installSessionLifecycle(lifecycle,()=>liveSession.lock(true));
lifecycle.dispatchEvent(new Event('visibilitychange'));
assert.equal(liveSession.getItem('auth'),'live-session');
const cached=new Event('pagehide');Object.defineProperty(cached,'persisted',{value:true});lifecycle.dispatchEvent(cached);
assert.equal(liveSession.getItem('auth'),'live-session');
lifecycle.dispatchEvent(new Event('pagehide'));assert.equal(liveSession.getItem('auth'),null);uninstall();
liveSession.beginAuthentication();liveSession.setItem('auth','cleanup-check');lifecycle.dispatchEvent(new Event('pagehide'));
assert.equal(liveSession.getItem('auth'),'cleanup-check');
const options=thisDeviceOptions({challenge:'AQID_w',rp:{id:'fravier3.github.io',name:'Finanzas'},user:{id:'BAUG',name:'test',displayName:'Test'},pubKeyCredParams:[{type:'public-key',alg:-7}],excludeCredentials:[{id:'BwgJ',type:'public-key'}],authenticatorSelection:{authenticatorAttachment:'cross-platform'}});
assert.equal(options.rp.id,'fravier3.github.io');assert.deepEqual([...new Uint8Array(options.challenge)],[1,2,3,255]);
assert.equal(options.authenticatorSelection.authenticatorAttachment,'platform');assert.equal(options.authenticatorSelection.residentKey,'required');assert.equal(options.authenticatorSelection.userVerification,'required');
assert.equal(encodeBase64url(options.excludeCredentials[0].id),'BwgJ');assert.equal(encodeBase64url(decodeBase64url('AQID_w')),'AQID_w');
console.log('Pruebas verificadas: finanzas, cancelación, sesión conservada al cambiar de app/bfcache, cierre real y opciones de clave del dispositivo.');
