import {useEffect,useRef,useState} from 'react';
import {Plus,Wallet,Settings2,ChevronLeft,ChevronRight,X,CalendarDays} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {type SavingsAccount,accountBalance,accountMonthly,nextContribution,accountContributions,updateSavingsAccount,today,dateFor,money,sum,months} from '../lib/finance';
const fullDate=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('es-PR',{day:'numeric',month:'short',year:'numeric'});
const COLORS=['#16a684','#315cf5','#8757e8','#ec5b86','#f3a53b','#38a6cf'];
export default function SavingsAccounts({accounts,busy,error,onSave,addRequest}:{accounts:SavingsAccount[];busy:boolean;error:string;onSave:(a:SavingsAccount)=>Promise<boolean>;addRequest:number}){
 const [editor,setEditor]=useState<SavingsAccount|null|undefined>(undefined),[selected,setSelected]=useState<string|null>(null);
 const lastAdd=useRef(addRequest);
 useEffect(()=>{if(addRequest!==lastAdd.current){lastAdd.current=addRequest;setEditor(null)}},[addRequest]);
 const current=accounts.find(a=>a.id===selected),now=today();
 const total=sum(accounts.map(a=>accountBalance(a,now)??0)),monthly=sum(accounts.map(a=>accountMonthly(a,now)));
 const year=Number(now.slice(0,4)),month=Number(now.slice(5,7))-1,day=Number(now.slice(8,10));
 const projection=(list:SavingsAccount[])=>Array.from({length:13},(_,n)=>{const index=month+n,date=n===0?now:dateFor(year+Math.floor(index/12),index%12,day);return {name:n===0?'Hoy':months[index%12]+' '+String(Number(date.slice(0,4))).slice(2),saldo:sum(list.map(a=>accountBalance(a,date)??0))}});
 const chart=projection(current?[current]:accounts);
 return <section className="panel savings-accounts"><div className="panel-heading"><div><h2>{current?current.name:'Mis cuentas de ahorro'}</h2><p>Saldo registrado + aportes programados. Separado del ahorro por cancelaciones.</p></div><button className="primary" disabled={busy} onClick={()=>setEditor(current??null)}>{current?<Settings2 size={18}/>:<Plus size={18}/>} {current?'Editar saldo y aportes':'Añadir cuenta de ahorro'}</button></div>
 {current&&<button className="back-button" onClick={()=>setSelected(null)}><ChevronLeft size={18}/>Volver a mis cuentas</button>}
 <div className="account-totals"><div><small>{current?'Saldo calculado hoy':'Total en mis cuentas hoy'}</small><strong>{money(current?accountBalance(current,now)??0:total)}</strong></div><div><small>Aportes mensuales programados</small><strong>{money(current?accountMonthly(current,now):monthly)}<span>/ mes</span></strong></div></div>
 <p className="field-note account-disclaimer">La app suma tus aportes al llegar cada fecha, incluso si no la abres. Es un cálculo manual: no se conecta a tu banco ni confirma depósitos o rendimientos. Corrige el saldo si hubo retiros, aportes distintos o cambios de valor.</p>
 {!accounts.length?<div className="empty small"><Wallet size={32}/><h3>Añade tu primera cuenta</h3><p>Indica lo que tienes hoy y cuánto aportarás cada mes.</p></div>:<>
 {!current&&<div className="service-grid">{accounts.map(a=>{const next=nextContribution(a,now);return <button className="service-card" key={a.id} onClick={()=>setSelected(a.id)}><div className="service-card-top"><span className="service-icon" style={{color:a.color,background:a.color+'14'}}><Wallet size={24}/></span><span className="soft-badge">Cuenta de ahorro</span><ChevronRight size={18}/></div><h3>{a.name}</h3><div className="service-price">{money(accountBalance(a,now)??0)}</div><div className="service-meta"><span>{money(accountMonthly(a,now))} de aporte mensual</span><span><CalendarDays size={15}/>{next?`Próximo: ${fullDate(next.date)}`:'Aportes pausados'}</span></div><div className="service-card-foot"><span>Saldo registrado {fullDate(a.snapshots.at(-1)!.date)}</span><b>{money(a.snapshots.at(-1)!.amount)}</b></div></button>})}</div>}
 <div className="panel-heading account-chart-heading"><div><h3>Proyección de tus ahorros</h3><p>Próximos 12 meses; sin intereses ni rendimientos.</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{left:0,right:12,top:8}}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#edf0f5"/><XAxis dataKey="name" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>'$'+v} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))}/><Area dataKey="saldo" name="Saldo calculado" stroke={current?.color??'#16a684'} fill={current?.color??'#16a684'} fillOpacity={.12} strokeWidth={3}/></AreaChart></ResponsiveContainer></div>
 {current&&<><h3>Último saldo registrado</h3><div className="breakdown-row"><span>{fullDate(current.snapshots.at(-1)!.date)}</span><b>{money(current.snapshots.at(-1)!.amount)}</b></div><h3>Aportes calculados desde ese saldo</h3>{accountContributions(current,current.snapshots.at(-1)!.date,now).map(p=><div className="breakdown-row" key={p.date}><span>{fullDate(p.date)}</span><b>+{money(p.amount)}</b></div>)}{!accountContributions(current,current.snapshots.at(-1)!.date,now).length&&<p className="field-note">Aún no ha llegado un aporte posterior a ese saldo.</p>}<details className="account-history"><summary>Historial de saldos y planes</summary>{[...current.snapshots].reverse().map(s=><div className="breakdown-row" key={s.id}><span>Saldo registrado · {fullDate(s.date)}</span><b>{money(s.amount)}</b></div>)}{current.plans.map(p=><div className="breakdown-row" key={p.id}><span>Aporte desde {fullDate(p.start)}{p.end?` hasta ${fullDate(p.end)} (excluido)`:''} · día {p.day}</span><b>{money(p.amount)}/mes</b></div>)}</details>{current.notes&&<p className="account-disclaimer">{current.notes}</p>}</>}
 </>}
 {editor!==undefined&&<AccountEditor account={editor} busy={busy} error={error} onClose={()=>setEditor(undefined)} onSave={async a=>{if(await onSave(a)){setEditor(undefined);setSelected(a.id)}}}/>}
 </section>;
}
function AccountEditor({account,busy,error,onClose,onSave}:{account:SavingsAccount|null;busy:boolean;error:string;onClose:()=>void;onSave:(a:SavingsAccount)=>Promise<void>}){
 const ref=useRef<HTMLDivElement>(null),[localError,setLocalError]=useState('');const now=today(),next=account?nextContribution(account,now):undefined;
 const d=new Date(now+'T12:00:00');const m=d.getMonth()+1;const defaultNext=next?.date??dateFor(d.getFullYear()+Math.floor(m/12),m%12,d.getDate());
 useEffect(()=>{const prior=document.activeElement as HTMLElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const els=ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input,textarea,select');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return ()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);prior?.focus()}},[busy]);
 return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label={account?'Editar cuenta de ahorro':'Añadir cuenta de ahorro'} ref={ref} tabIndex={-1}><div className="modal-heading"><h2>{account?'Editar cuenta de ahorro':'Añadir cuenta de ahorro'}</h2><button className="icon-button" aria-label="Cerrar cuenta de ahorro" disabled={busy} onClick={onClose}><X size={21}/></button></div><form className="editor-form" onSubmit={async e=>{e.preventDefault();setLocalError('');const f=new FormData(e.currentTarget);try{const nextDate=String(f.get('next'));const a=updateSavingsAccount(account??undefined,{name:String(f.get('name')),color:String(f.get('color')),notes:String(f.get('notes')),balance:Number(f.get('balance')),monthly:Number(f.get('monthly')),next:nextDate,day:Number(nextDate.slice(8,10))});await onSave(a)}catch(e){setLocalError((e as Error).message)}}}>
 <label>Nombre de la cuenta<input name="name" required maxLength={100} placeholder="Ej. Acorns, cuenta del banco…" defaultValue={account?.name??''}/></label>
 <div className="form-grid"><label>Saldo actual en USD<input name="balance" required type="number" min="0" max="9999999" step="0.01" inputMode="decimal" defaultValue={account?accountBalance(account,now)??0:''} placeholder="453.00"/></label><label>Aporte mensual en USD<input name="monthly" required type="number" min="0" max="9999999" step="0.01" inputMode="decimal" defaultValue={account?accountMonthly(account,now):''} placeholder="100.00"/></label></div>
 <p className="field-note">Este saldo corresponde a hoy, {fullDate(now)}, e incluye los movimientos de hoy. No se vuelven a sumar aportes anteriores. Pon el aporte mensual en 0 para pausarlo.</p>
 <div className="form-grid"><label>Fecha del próximo aporte<input name="next" required type="date" min={now} defaultValue={defaultNext}/></label><label>Color<select name="color" defaultValue={account?.color??COLORS[0]}>{COLORS.map((c,n)=><option key={c} value={c}>{['Verde','Azul','Violeta','Rosa','Ámbar','Celeste'][n]}</option>)}{account&&!COLORS.includes(account.color)&&<option value={account.color}>{account.color}</option>}</select></label></div>
 <p className="field-note">Se suma una vez al mes, el día de la fecha elegida. Si el mes es más corto, se usa su último día. Cambiar el saldo registra una corrección desde hoy; no altera los saldos anteriores.</p>
 <label>Notas<textarea name="notes" rows={3} maxLength={2000} defaultValue={account?.notes??''} placeholder="Meta de ahorro, detalles…"/></label>
 {(localError||error)&&<div className="error" role="alert">{localError||error}</div>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar cuenta de ahorro'}</button></div></form></div></div>;
}
